### ISSUE TITLE
Permettre de styler différentes sections dans la page d'acceuil

### ISSUE THREAD

**Issue by DavidBruant** [betagouv/azur.comobi.fr#39]
On a eu le problème avec azur.comobi où il était [pertinent de styler spéciquement la section FAQ](
https://github.com/betagouv/comobi_valberg/pull/24/files/ebb298233e90c57ce707fb745db1ec743153a7ff#diff-6a4c17c5d12a55909d4ef044a7a316e845da618a2387f5cb4a80bdb85c192d11)

Mais ptèt que ça serait utile de rendre ce mécanisme générique

Actuellement, on cherche spécifiquement `<!--faq -->`, puis on split le document en 2 sections :

```md
{% assign sections = content | split: "<!--faq -->" %}
<section class="content">
  {{ sections[0] }}
</section>
<section class="content faq">
  {{ sections[1] }}
</section> 
```

Puis, on [stylise avec la classe `.faq`](https://github.com/betagouv/comobi_valberg/pull/24/files#diff-acac5642e87ae8c98587f22f966870bda360916d632749c959ffd1ad4c56d62aR147-R149):

```css
.faq {
	background-color: $faq-color;
}
```

Une autre approche, ça serait de : 
- faire un split sur quelque chose de générique genre `<!-- section -->` 
- faire une boucle pour générer une `<section>` par morceau
- styliser avec les selecteurs nth-of-type:
```css
parent > section:nth-child(1){
  background-color: $section-color-1;
}
parent > section:nth-child(2){
  background-color: $section-color-2;
}
```

Les variables `$section-color-x` peuvent être créés à partir d'une liste de couleurs fournie dans le config.yml
